# GitHub Actions workflow for mutation testing with pytest-gremlins
#
# This workflow runs mutation testing and optionally uploads results to:
# - Stryker Dashboard (for mutation score badge)
# - SonarQube (for issue tracking)
#
# Copy this file to .github/workflows/mutation.yml in your project.

name: Mutation Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.12"
  MIN_MUTATION_SCORE: 80

jobs:
  mutation-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for SonarQube

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"

      - name: Run mutation testing
        run: |
          pytest --gremlins --gremlin-report=json,html

      - name: Check mutation score threshold
        run: |
          SCORE=$(python -c "import json; print(json.load(open('gremlin-report.json'))['summary']['percentage'])")
          echo "Mutation score: $SCORE%"
          if (( $(echo "$SCORE < ${{ env.MIN_MUTATION_SCORE }}" | bc -l) )); then
            echo "::error::Mutation score $SCORE% is below threshold ${{ env.MIN_MUTATION_SCORE }}%"
            exit 1
          fi

      # Optional: Upload to Stryker Dashboard for badge
      - name: Upload to Stryker Dashboard
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: |
          # Create score-only JSON for badge
          python -c "
          import json
          data = json.load(open('gremlin-report.json'))
          print(json.dumps({'mutationScore': data['summary']['percentage']}))
          " > mutation-score.json

          # Upload to dashboard
          curl -X PUT \
            -H 'Content-Type: application/json' \
            -H "X-Api-Key: $STRYKER_DASHBOARD_API_KEY" \
            --data-binary @mutation-score.json \
            "https://dashboard.stryker-mutator.io/api/reports/github.com/${{ github.repository }}/${{ github.ref_name }}"

      # Optional: Convert to SonarQube format
      - name: Generate SonarQube report
        if: github.event_name == 'push'
        run: |
          python -c "
          import json
          from pathlib import Path

          data = json.load(open('gremlin-report.json'))

          issues = []
          for result in data['results']:
              if result['status'] == 'survived':
                  issues.append({
                      'engineId': 'pytest-gremlins',
                      'ruleId': f\"mutant-survived-{result['operator']}\",
                      'severity': 'MAJOR',
                      'type': 'CODE_SMELL',
                      'effortMinutes': 10,
                      'primaryLocation': {
                          'filePath': result['file_path'],
                          'textRange': {'startLine': result['line_number']},
                          'message': f\"Mutant survived: {result['description']}\"
                      }
                  })

          Path('mutation-sonar.json').write_text(json.dumps({'issues': issues}, indent=2))
          "

      # Optional: SonarQube scan
      - name: SonarQube Scan
        if: github.event_name == 'push'
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.externalIssuesReportPaths=mutation-sonar.json
        continue-on-error: true  # Don't fail if SonarQube is not configured

      - name: Upload mutation reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutation-reports
          path: |
            gremlin-report.html
            gremlin-report.json
            mutation-sonar.json
          retention-days: 30

  # Add PR comment with mutation score
  mutation-score-comment:
    runs-on: ubuntu-latest
    needs: mutation-testing
    if: github.event_name == 'pull_request'

    steps:
      - name: Download mutation reports
        uses: actions/download-artifact@v4
        with:
          name: mutation-reports

      - name: Post PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('gremlin-report.json', 'utf8'));
            const summary = report.summary;

            const survivors = report.results
              .filter(r => r.status === 'survived')
              .slice(0, 10)
              .map(r => `- \`${r.file_path}:${r.line_number}\` - ${r.description}`)
              .join('\n');

            const body = `## Mutation Testing Results

            | Metric | Value |
            |--------|-------|
            | **Score** | ${summary.percentage.toFixed(1)}% |
            | **Zapped** | ${summary.zapped} |
            | **Survived** | ${summary.survived} |
            | **Total** | ${summary.total} |

            ${summary.survived > 0 ? `### Top Surviving Mutants\n${survivors}` : ''}

            ---
            *Generated by pytest-gremlins*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
